python -m src.scripts.init_retrieval --language en --partition train --task_key diann_2023_t1
python -m src.scripts.init_retrieval --language es --partition train --task_key diann_2023_t1
python -m src.scripts.init_retrieval --language en --partition train --task_key dipromats_2023_t1
python -m src.scripts.init_retrieval --language es --partition train --task_key dipromats_2023_t1
python -m src.scripts.init_retrieval --language en --partition train --task_key dipromats_2023_t2
python -m src.scripts.init_retrieval --language es --partition train --task_key dipromats_2023_t2
python -m src.scripts.init_retrieval --language en --partition train --task_key dipromats_2023_t3
python -m src.scripts.init_retrieval --language es --partition train --task_key dipromats_2023_t3
python -m src.scripts.init_retrieval --language en --partition train --task_key exist_2022_t1
python -m src.scripts.init_retrieval --language es --partition train --task_key exist_2022_t1
python -m src.scripts.init_retrieval --language en --partition train --task_key exist_2022_t2
python -m src.scripts.init_retrieval --language es --partition train --task_key exist_2022_t2
python -m src.scripts.init_retrieval --language en --partition train --task_key exist_2023_t1
python -m src.scripts.init_retrieval --language es --partition train --task_key exist_2023_t1
python -m src.scripts.init_retrieval --language en --partition train --task_key exist_2023_t2
python -m src.scripts.init_retrieval --language es --partition train --task_key exist_2023_t2
python -m src.scripts.init_retrieval --language en --partition train --task_key exist_2023_t3
python -m src.scripts.init_retrieval --language es --partition train --task_key exist_2023_t3
python -m src.scripts.init_retrieval --language en --partition train --task_key sqac_squad_2024_t1
python -m src.scripts.init_retrieval --language es --partition train --task_key sqac_squad_2024_t1
